### ISSUE TITLE
MQTT credentials

### ISSUE THREAD

**Issue by favarinbarracano** [ipodmusicman/paradox-controller#3]
Hi,
in case of MQTT protected broker with user and password I edited the sketch:
#define mqttUser "XXXXXX"
#define mqttPassword "XXXXXX"
if (client.connect(charBuf, mqttUser, mqttPassword, topicStatus, 0, true, "offline")) {

The sketch now is able to connect to MQTT protected broker.
Any suggestion?

Manuel,
Thanks

**Comment by ipodmusicman** [comment]
Thanks for the suggestion.  When I work on it again, I'll look at making the username / password for MQTT configurable.
